### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removesuffix'

### ISSUE THREAD

**Issue by pysiak** [evdenis/cvehound#1]
Hi, getting some errors:
```
solt@Holodeck:~$ python3 -V
Python 3.8.5
solt@Holodeck:~$ cvehound --dir ~/workspace/linux-source-5.4.0 --verbose
Traceback (most recent call last):
  File "/home/solt/.local/bin/cvehound", line 8, in <module>
    sys.exit(main())
  File "/home/solt/.local/lib/python3.8/site-packages/cvehound/__init__.py", line 142, in main
    known_cves = get_all_cves()
  File "/home/solt/.local/lib/python3.8/site-packages/cvehound/__init__.py", line 124, in get_all_cves
    return [cve.removesuffix('.cocci').removesuffix('.grep')
  File "/home/solt/.local/lib/python3.8/site-packages/cvehound/__init__.py", line 124, in <listcomp>
    return [cve.removesuffix('.cocci').removesuffix('.grep')
AttributeError: 'str' object has no attribute 'removesuffix'```

**Comment by evdenis** [comment]
Fixed in commit https://github.com/evdenis/cvehound/commit/277ac71ecf71f5c13a79b754ff26c704a79aaf83. Thanks!
