### ISSUE TITLE
Earliest version of Linux kernel that is supported?

### ISSUE THREAD

**Issue by armijnhemel** [evdenis/cvehound#30]
I couldn't find anywhere which versions of the Linux kernel are supported. I tried with a `2.4` source tree and got this error:

```
$ cvehound -k=/tmp/src/EdiLinux/linux-2.4.18-adm/
Traceback (most recent call last):
  File "/nix/store/ibiwly61jv0gz5fjxfcv6y3absgwhiwp-cvehound-1.0.4/bin/.cvehound-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ibiwly61jv0gz5fjxfcv6y3absgwhiwp-cvehound-1.0.4/lib/python3.9/site-packages/cvehound/__main__.py", line 128, in main
    report['kernel'] = get_kernel_version(cmdargs.kernel)
  File "/nix/store/ibiwly61jv0gz5fjxfcv6y3absgwhiwp-cvehound-1.0.4/lib/python3.9/site-packages/cvehound/util.py", line 48, in get_kernel_version
    version['name'] = getparam()
  File "/nix/store/ibiwly61jv0gz5fjxfcv6y3absgwhiwp-cvehound-1.0.4/lib/python3.9/site-packages/cvehound/util.py", line 43, in getparam
    return line.split('=')[1].strip()
IndexError: list index out of range
```

(don't worry about the strange paths, I am deploying `cvehound` with Nix)

Is `2.4` too old to be scanned?

**Comment by evdenis** [comment]
Hi, I didn't test versions prior v2.6.12-rc2 (first git commit). Generally speaking there should be no limits on linux kernel versions. I see the problem from the log you provided and it should be easy to fix. I'll write here after I fix it. Thanks!
